[Hooked Modules]
ExempleFiltreCollectionStandard.exe=T
[Non-Hooked Modules]
Secur32.dll=T
oleaut32.dll=T
msvcrt.dll=T
ole32.dll=T
IMM32.DLL=T
MSCTF.dll=T
SXS.DLL=T
COMRes.dll=T
CLBCATQ.DLL=T
cbasesql.dll=T
cbaselocal.dll=T
PSAPI.DLL=T
SHFOLDER.dll=T
cbaseintf.dll=T
mlcorert.dll=T
MSVCP71.dll=T
MSVCR71.dll=T
objets100.dll=T
MSDART.DLL=T
msado15.dll=T
xpsp2res.dll=T
OLEDB32R.DLL=T
oledb32.dll=T
MSASN1.dll=T
CRYPT32.dll=T
MSVCR80.dll=T
sqlncli.dll=T
SQLNCLIR.RLL=T
MSWSTR10.DLL=T
MSWDAT10.DLL=T
USERENV.dll=T
RESUTILS.DLL=T
CLUSAPI.DLL=T
MTXCLU.DLL=T
colbact.DLL=T
comsvcs.dll=T
cryptdll.dll=T
kerberos.dll=T
iphlpapi.dll=T
msv1_0.dll=T
ntdsapi.dll=T
security.dll=T
schannel.dll=T
instapi.dll=T
dssenh.dll=T
rsaenh.dll=T
msadrh15.dll=T
msadce.dll=T
msadcer.dll=T
[Search Dirs]
C:\Program Files\Borland\Delphi7\\Bin\=T
C:\Program Files\Borland\Delphi7\\Imports\=T
C:\Program Files\Borland\Delphi7\\Lib\=T
C:\Program Files\Borland\Delphi7\\Projects\Bpl\=T
C:\Program Files\Indy 10 for Delphi 7\LibD7\=T
C:\Program Files\Borland\Delphi7\\Source\VCL\=T
C:\Program Files\Borland\Delphi7\\Source\RTL\Sys\=T
M:\My_Dropbox\Delphi7_projets\Tests\OM\ExempleFiltreCollectionStandard\=T
